{{- if and .Values.git.enabled (not .Values.git.existingSecret) .Values.git.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "editor.gitSecretName" . }}
  labels:
    {{- include "editor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.git.existingSecretKey | default "token" }}: {{ .Values.git.token | quote }}
{{- end }}
