$schema: https://json-schema.org/draft/2020-12/schema
title: SeaDOTs Catalog Application Package
description: >
  APKG/CWL-aligned computational contract for a reusable SeaDOTs
  application.

allOf:
  - $ref: https://ogcincubator.github.io/bblocks-openscience/build/annotated/osc/application-package/schema.yaml

type: object
properties:
  type:
    const: ApplicationPackage
  softwareVersion:
    type: string
  programmingLanguage:
    type: string
additionalProperties: true
